apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: dmpelletier1989/proxy-service
          ports:
            - containerPort: 5000
